Added option in sascfg for HTML 4.0 as alternative to HTLM 5.0 (#38)
* Added option in sascfg for HTML 4.0 as alternative to HTLM 5.0

Using PROC TEMPLATE with "ods html5" (HTML 5.0) can cause some problems
which do not happen when using "ods html" (HTML 4.0).  There are
probably other reasons why some people might want to use HTML 4.0 too.
Thus I added an option in sascfg.py to be able to use HTML 4.0.

* Added important notes about html4 and images

* comment about local + concatenated + default html5 + error if non-local

* Great modifs made by Tom Weber (https://github.com/tomweber-sas)

1) can't error out in SASconfig[IOM|STDIO], need to check in _startsas for local mode
2) need to catch: AttributeError: module 'saspy.sascfg_personal' has no attribute 'SAS_output_options'
   because no one has this attribute in their sascfg.py currently. Can't break anyone using this already.
3) 'default' and 'winlocal' are just made up names. Can refer to them in the templates,
   but users can have any config names they want to use.
4) odsopen isn't identical between IOM and STDIO (I think you cut-n-paste IOM into STDIO)

* Fix file location for PR

Moved files to the correct location. Not other changes mage.

* Signed-off by AJM

Signed-off-by: Alexia Jolicoeur-Martineau <alexia.jolicoeur-martineau@mail.mcgill.ca>