Great modifs made by Tom Weber (https://github.com/tomweber-sas)
1) can't error out in SASconfig[IOM|STDIO], need to check in _startsas for local mode
2) need to catch: AttributeError: module 'saspy.sascfg_personal' has no attribute 'SAS_output_options'
   because no one has this attribute in their sascfg.py currently. Can't break anyone using this already.
3) 'default' and 'winlocal' are just made up names. Can refer to them in the templates,
   but users can have any config names they want to use.
4) odsopen isn't identical between IOM and STDIO (I think you cut-n-paste IOM into STDIO)